/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#if HAVE_WINSOCK2_H
# include <winsock2.h> /* avoid mingw pollution on DATADIR */
#endif
#define PREFIX "/home/ritesh/rc-car/ros2ws/libs/bison"
#define EXEC_PREFIX "/home/ritesh/rc-car/ros2ws/libs/bison"
#define BINDIR "/home/ritesh/rc-car/ros2ws/libs/bison/bin"
#define SBINDIR "/home/ritesh/rc-car/ros2ws/libs/bison/sbin"
#define LIBEXECDIR "/home/ritesh/rc-car/ros2ws/libs/bison/libexec"
#define DATAROOTDIR "/home/ritesh/rc-car/ros2ws/libs/bison/share"
#define DATADIR "/home/ritesh/rc-car/ros2ws/libs/bison/share"
#define SYSCONFDIR "/home/ritesh/rc-car/ros2ws/libs/bison/etc"
#define SHAREDSTATEDIR "/home/ritesh/rc-car/ros2ws/libs/bison/com"
#define LOCALSTATEDIR "/home/ritesh/rc-car/ros2ws/libs/bison/var"
#define RUNSTATEDIR "/home/ritesh/rc-car/ros2ws/libs/bison/var/run"
#define INCLUDEDIR "/home/ritesh/rc-car/ros2ws/libs/bison/include"
#define OLDINCLUDEDIR "/usr/include"
#define DOCDIR "/home/ritesh/rc-car/ros2ws/libs/bison/share/doc/bison"
#define INFODIR "/home/ritesh/rc-car/ros2ws/libs/bison/share/info"
#define HTMLDIR "/home/ritesh/rc-car/ros2ws/libs/bison/share/doc/bison"
#define DVIDIR "/home/ritesh/rc-car/ros2ws/libs/bison/share/doc/bison"
#define PDFDIR "/home/ritesh/rc-car/ros2ws/libs/bison/share/doc/bison"
#define PSDIR "/home/ritesh/rc-car/ros2ws/libs/bison/share/doc/bison"
#define LIBDIR "/home/ritesh/rc-car/ros2ws/libs/bison/lib"
#define LISPDIR "/home/ritesh/rc-car/ros2ws/libs/bison/share/emacs/site-lisp"
#define LOCALEDIR "/home/ritesh/rc-car/ros2ws/libs/bison/share/locale"
#define MANDIR "/home/ritesh/rc-car/ros2ws/libs/bison/share/man"
#define PKGDATADIR "/home/ritesh/rc-car/ros2ws/libs/bison/share/bison"
#define PKGINCLUDEDIR "/home/ritesh/rc-car/ros2ws/libs/bison/include/bison"
#define PKGLIBDIR "/home/ritesh/rc-car/ros2ws/libs/bison/lib/bison"
#define PKGLIBEXECDIR "/home/ritesh/rc-car/ros2ws/libs/bison/libexec/bison"
